import { StyleSheet } from "react-native";

export const paymentStyles = StyleSheet.create({
  flex: { flex: 1 },
  header: { minHeight: 66, flexDirection: "row", alignItems: "center", paddingHorizontal: 16, borderBottomWidth: 1, gap: 12 },
  iconButton: { width: 42, height: 42, alignItems: "center", justifyContent: "center" },
  headerCopy: { flex: 1 },
  headerTitle: { fontSize: 18, fontFamily: "Raleway_800ExtraBold" },
  headerSubtitle: { marginTop: 2, fontSize: 12, fontFamily: "Raleway_500Medium" },
  timer: { minHeight: 42, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "center" },
  timerText: { fontSize: 12, fontFamily: "Raleway_600SemiBold" },
  timerValue: { marginLeft: 6, fontSize: 14, fontFamily: "Raleway_800ExtraBold", fontVariant: ["tabular-nums"] },
  content: { padding: 16, paddingBottom: 36, gap: 18 },
  progress: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  progressItem: { flex: 1, alignItems: "center", gap: 6 },
  progressDot: { width: 28, height: 28, borderRadius: 14, alignItems: "center", justifyContent: "center" },
  progressNumber: { color: "#fff", fontSize: 13, fontFamily: "Raleway_800ExtraBold" },
  progressLabel: { fontSize: 12, fontFamily: "Raleway_700Bold" },
  loading: { minHeight: 300, alignItems: "center", justifyContent: "center", gap: 14, paddingHorizontal: 24 },
  muted: { fontSize: 14, fontFamily: "Raleway_500Medium" },
  errorText: { textAlign: "center", fontSize: 15, lineHeight: 21, fontFamily: "Raleway_600SemiBold" },
  summary: { borderWidth: 1, borderRadius: 8, padding: 16 },
  summaryHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
  eyebrow: { fontSize: 11, fontFamily: "Raleway_800ExtraBold" },
  summaryTitle: { marginTop: 3, fontSize: 20, fontFamily: "Raleway_800ExtraBold" },
  itemRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", paddingVertical: 11, gap: 12 },
  itemCopy: { flex: 1 },
  itemName: { fontSize: 15, lineHeight: 20, fontFamily: "Raleway_700Bold" },
  itemQty: { marginTop: 3, fontSize: 12, fontFamily: "Raleway_500Medium" },
  itemPrice: { fontSize: 14, fontFamily: "Raleway_700Bold" },
  totalBlock: { borderTopWidth: 1, paddingTop: 12, marginTop: 4, gap: 8 },
  summaryLine: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  summaryLineLabel: { fontSize: 13, fontFamily: "Raleway_500Medium" },
  summaryLineValue: { fontSize: 13, fontFamily: "Raleway_700Bold" },
  grandTotalRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 3 },
  grandTotalLabel: { fontSize: 17, fontFamily: "Raleway_800ExtraBold" },
  grandTotalValue: { fontSize: 22, fontFamily: "Raleway_800ExtraBold" },
  section: { gap: 12 },
  sectionTitleRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  sectionTitle: { fontSize: 17, fontFamily: "Raleway_800ExtraBold" },
  helper: { fontSize: 13, lineHeight: 18, fontFamily: "Raleway_500Medium" },
  couponRow: { flexDirection: "row", gap: 10 },
  couponInput: { flex: 1 },
  input: { minHeight: 50, borderWidth: 1, borderRadius: 8, paddingHorizontal: 14, fontSize: 16, fontFamily: "Raleway_600SemiBold" },
  smallButton: { minHeight: 50, minWidth: 105, borderRadius: 8, alignItems: "center", justifyContent: "center", paddingHorizontal: 16 },
  smallButtonText: { color: "#fff", fontSize: 14, fontFamily: "Raleway_800ExtraBold" },
  appliedCoupon: { minHeight: 50, borderRadius: 8, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  appliedCouponText: { flex: 1, fontSize: 13, fontFamily: "Raleway_700Bold" },
  removeText: { fontSize: 13, fontFamily: "Raleway_800ExtraBold" },
  inlineMessage: { borderWidth: 1, borderRadius: 8, padding: 11, flexDirection: "row", alignItems: "flex-start", gap: 8 },
  inlineMessageText: { flex: 1, fontSize: 12, lineHeight: 17, fontFamily: "Raleway_600SemiBold" },
  methodList: { gap: 9 },
  method: { minHeight: 74, borderWidth: 1.5, borderRadius: 8, padding: 12, flexDirection: "row", alignItems: "center", gap: 12 },
  methodIcon: { width: 42, height: 42, borderRadius: 21, alignItems: "center", justifyContent: "center" },
  methodCopy: { flex: 1 },
  methodTitle: { fontSize: 15, fontFamily: "Raleway_700Bold" },
  methodDescription: { marginTop: 3, fontSize: 12, lineHeight: 16, fontFamily: "Raleway_500Medium" },
  radio: { width: 22, height: 22, borderRadius: 11, borderWidth: 2, alignItems: "center", justifyContent: "center" },
  radioInner: { width: 10, height: 10, borderRadius: 5 },
  phoneBlock: { gap: 7 },
  label: { fontSize: 13, fontFamily: "Raleway_700Bold" },
  zeroTotal: { minHeight: 56, borderRadius: 8, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", gap: 10 },
  zeroTotalText: { flex: 1, fontSize: 14, fontFamily: "Raleway_700Bold" },
  message: { borderWidth: 1, borderRadius: 8, padding: 13, flexDirection: "row", alignItems: "flex-start", gap: 10 },
  messageText: { flex: 1, fontSize: 13, lineHeight: 18, fontFamily: "Raleway_600SemiBold" },
  footer: { borderTopWidth: 1, paddingHorizontal: 16, paddingTop: 10, paddingBottom: 10, gap: 8 },
  payButton: { minHeight: 56, borderRadius: 8, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9, paddingHorizontal: 18 },
  payButtonText: { color: "#fff", fontSize: 16, fontFamily: "Raleway_800ExtraBold" },
  statusHint: { textAlign: "center", fontSize: 12, lineHeight: 17, fontFamily: "Raleway_500Medium" },
  checkButton: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  checkButtonText: { fontSize: 14, fontFamily: "Raleway_800ExtraBold" },
});
