import { StyleSheet } from "react-native";

export const paymentStyles = StyleSheet.create({
  flex: { flex: 1 },
  header: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    gap: 12,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCopy: { flex: 1 },
  headerTitle: { fontSize: 18, fontFamily: "Raleway_800ExtraBold" },
  headerSubtitle: {
    marginTop: 2,
    fontSize: 12,
    fontFamily: "Raleway_500Medium",
  },
  timer: {
    minHeight: 44,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  timerText: { fontSize: 12, fontFamily: "Raleway_600SemiBold" },
  timerValue: {
    marginLeft: 6,
    fontSize: 14,
    fontFamily: "Raleway_800ExtraBold",
    fontVariant: ["tabular-nums"],
  },
  content: { padding: 16, paddingBottom: 72, gap: 16 },
  progress: {
    minHeight: 66,
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  progressGroup: { flex: 1, flexDirection: "row", alignItems: "center" },
  progressItem: { alignItems: "center", gap: 5 },
  progressConnector: {
    flex: 1,
    height: 1,
    marginHorizontal: 8,
    marginBottom: 19,
  },
  progressDot: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  progressNumber: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Raleway_800ExtraBold",
  },
  progressLabel: { fontSize: 12, fontFamily: "Raleway_700Bold" },
  loading: {
    minHeight: 300,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    paddingHorizontal: 24,
  },
  muted: { fontSize: 14, fontFamily: "Raleway_500Medium" },
  errorText: {
    textAlign: "center",
    fontSize: 15,
    lineHeight: 21,
    fontFamily: "Raleway_600SemiBold",
  },
  summary: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    gap: 10,
  },
  summaryHeaderCopy: { flex: 1, minWidth: 0 },
  ticketCountBadge: {
    minHeight: 36,
    borderRadius: 8,
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  ticketCountText: { fontSize: 11, fontFamily: "Raleway_800ExtraBold" },
  eyebrow: { fontSize: 11, fontFamily: "Raleway_800ExtraBold" },
  summaryTitle: {
    marginTop: 3,
    fontSize: 20,
    fontFamily: "Raleway_800ExtraBold",
  },
  itemRow: {
    position: "relative",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    minHeight: 84,
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    paddingLeft: 16,
    marginBottom: 8,
    gap: 12,
    overflow: "hidden",
  },
  itemAccent: { position: "absolute", left: 0, top: 0, bottom: 0, width: 3 },
  itemCopy: { flex: 1 },
  itemType: { marginBottom: 3, fontSize: 9, fontFamily: "Raleway_800ExtraBold" },
  itemName: { fontSize: 15, lineHeight: 20, fontFamily: "Raleway_700Bold" },
  itemQty: { marginTop: 3, fontSize: 12, fontFamily: "Raleway_500Medium" },
  seatRow: {
    marginTop: 7,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  seatText: { fontSize: 13, fontFamily: "Raleway_800ExtraBold" },
  itemPrice: {
    flexShrink: 0,
    fontSize: 14,
    fontFamily: "Raleway_700Bold",
  },
  totalBlock: { borderTopWidth: 1, paddingTop: 12, marginTop: 4, gap: 8 },
  summaryLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  summaryLineLabel: { fontSize: 13, fontFamily: "Raleway_500Medium" },
  summaryLineValue: { fontSize: 13, fontFamily: "Raleway_700Bold" },
  discountRow: { borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8 },
  grandTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 3,
  },
  grandTotalLabel: { fontSize: 17, fontFamily: "Raleway_800ExtraBold" },
  grandTotalValue: { fontSize: 22, fontFamily: "Raleway_800ExtraBold" },
  section: { gap: 12, borderWidth: 1, borderRadius: 16, padding: 16 },
  sectionTitleRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  sectionTitle: { fontSize: 17, fontFamily: "Raleway_800ExtraBold" },
  helper: { fontSize: 13, lineHeight: 18, fontFamily: "Raleway_500Medium" },
  couponRow: { flexDirection: "row", gap: 10 },
  couponInput: { flex: 1 },
  input: {
    minHeight: 52,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    fontSize: 16,
    fontFamily: "Raleway_600SemiBold",
  },
  smallButton: {
    minHeight: 52,
    minWidth: 105,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  smallButtonText: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Raleway_800ExtraBold",
  },
  appliedCoupon: {
    minHeight: 50,
    borderRadius: 8,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  appliedCouponText: { flex: 1, fontSize: 13, fontFamily: "Raleway_700Bold" },
  removeText: { fontSize: 13, fontFamily: "Raleway_800ExtraBold" },
  inlineMessage: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 11,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  inlineMessageText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 17,
    fontFamily: "Raleway_600SemiBold",
  },
  methodList: { gap: 9 },
  method: {
    minHeight: 74,
    borderWidth: 1.5,
    borderRadius: 14,
    overflow: "hidden",
  },
  methodMain: {
    minHeight: 74,
    padding: 12,
    paddingLeft: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  methodAccent: {
    position: "absolute",
    left: 0,
    top: 12,
    bottom: 12,
    width: 3,
    borderRadius: 2,
  },
  methodIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  methodLogo: { width: 34, height: 34 },
  methodCopy: { flex: 1 },
  methodTitle: { fontSize: 15, fontFamily: "Raleway_700Bold" },
  methodDescription: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 16,
    fontFamily: "Raleway_500Medium",
  },
  radio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  radioInner: { width: 10, height: 10, borderRadius: 5 },
  methodExpansion: {
    borderTopWidth: 1,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 14,
  },
  providerHint: { flexDirection: "row", alignItems: "center", gap: 8 },
  phoneBlock: { gap: 7 },
  label: { fontSize: 13, fontFamily: "Raleway_700Bold" },
  phoneHelper: {
    fontSize: 11,
    lineHeight: 16,
    fontFamily: "Raleway_500Medium",
  },
  couponToggle: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  couponToggleText: { flex: 1, fontSize: 15, fontFamily: "Raleway_700Bold" },
  zeroTotal: {
    minHeight: 56,
    borderRadius: 8,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  zeroTotalText: { flex: 1, fontSize: 14, fontFamily: "Raleway_700Bold" },
  message: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 13,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  messageText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: "Raleway_600SemiBold",
  },
  footer: {
    borderTopWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: -4 },
    elevation: 8,
  },
  payButton: {
    minHeight: 56,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    paddingHorizontal: 18,
  },
  payButtonText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Raleway_800ExtraBold",
  },
  statusHint: {
    textAlign: "center",
    fontSize: 12,
    lineHeight: 17,
    fontFamily: "Raleway_500Medium",
  },
  checkButton: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  checkButtonText: { fontSize: 14, fontFamily: "Raleway_800ExtraBold" },
});
